services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-imersao-alura:latest
    container_name: api-imersao-alura
    ports:
      - "8000:8000"
    volumes:
      # Monta um volume para persistir o banco SQLite
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
